//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Archer:UnitBase
{
	public Archer ()
	{
		unitType = UnitTypes.ARCHER;
		this.attackPower = 70;
		this.defensePower = 30;
		this.range = 4;
		this.maxHP = 900;
		this.HP = maxHP;
		criticalRate = 10;
		criticalFactor = 1.5f;
		coolDown = 1.5f;
		coolDownFactor = 0f;
		movingSpeed = 2f;
	}
	public override float getAttackPower(UnitBase targetUnit)
	{
		int targetUnitType = targetUnit.unitType;
		float newAttackPower = attackPower;
		if (targetUnitType == UnitTypes.ROGUE)
			newAttackPower *= 1f;
		else if (targetUnitType == UnitTypes.SHAMAN)
			newAttackPower *= 1f;
		return newAttackPower;
	}
	public override float getDefensePower(UnitBase AttackerUnit)
	{
		int AttackerUnitType = AttackerUnit.unitType;
		float newDefensePower = defensePower;
		if (AttackerUnitType == UnitTypes.SHAMAN)
			newDefensePower *= 0.8f;
		if (AttackerUnitType == UnitTypes.ROGUE)
			newDefensePower *= 1.1f;
		return newDefensePower;
	}
}

