//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Rogue: UnitBase
{
	public Rogue ()
	{
		unitType = UnitTypes.ROGUE;
		this.attackPower = 200;
		this.defensePower = 45;
		this.range = 2;
		this.maxHP = 1200;
		this.HP = maxHP;
		criticalRate = 10;
		criticalFactor = 7.5f;
		coolDown = 2f;
		coolDownFactor = 0f;
		movingSpeed = 4f;
	}
	public override float getAttackPower(UnitBase targetUnit)
	{
		int targetUnitType = targetUnit.unitType;
		float newAttackPower = attackPower;
		if (targetUnitType == UnitTypes.TANK)
			newAttackPower *= 1f;
		if (targetUnitType == UnitTypes.ARCHER)
			newAttackPower *= 1f;
		if (targetUnit.getHP () < targetUnit.getMaxHP () * 0.3)
			newAttackPower *= 1f;
		return newAttackPower;
	}
	public override float getDefensePower(UnitBase AttackerUnit)
	{
		int AttackerUnitType = AttackerUnit.unitType;
		float newDefensePower = defensePower;
		if (AttackerUnitType == UnitTypes.ARCHER)
			newDefensePower *= 0.9f;
		if (AttackerUnitType == UnitTypes.TANK)
			newDefensePower *= 1.1f;
		return newDefensePower;
	}
}
