//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Shaman: UnitBase
{
	public Shaman ()
	{
		unitType = UnitTypes.SHAMAN;
		this.attackPower = 140;
		this.defensePower = 50;
		this.range = 2;
		this.maxHP = 1200;
		this.HP = maxHP;
		criticalRate = 30;
		criticalFactor = 2f;
		coolDown = 2.5f;
		coolDownFactor = 0f;
	}
	public override float getAttackPower(UnitBase targetUnit)
	{
		int targetUnitType = targetUnit.unitType;
		float newAttackPower = attackPower;
		if (targetUnitType == UnitTypes.ARCHER)
			newAttackPower *= 1f;
		if (targetUnitType == UnitTypes.MAGE)
			newAttackPower *= 1f;
		return newAttackPower;
	}
	public override float getDefensePower(UnitBase AttackerUnit)
	{
		int AttackerUnitType = AttackerUnit.unitType;
		float newDefensePower = defensePower;
		if (AttackerUnitType == UnitTypes.MAGE)
			newDefensePower *= 0.8f;
		if (AttackerUnitType == UnitTypes.ARCHER)
			newDefensePower *= 1.2f;
		return newDefensePower;
	}
}

