//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;
public class TargetComparer:IComparer <Unit>
{
	private bool isEnemy;
	private int fromRow;
	public TargetComparer (bool enemy)
	{
		this.isEnemy = enemy;
	}
	public int Compare(Unit x, Unit y)
	{
		int result = 0;
		float xPosition = x.transform.position.x;
		float yPosition = y.transform.position.x;
		if(x.isLeader) xPosition = 1000;
		if(y.isLeader) yPosition = 1000;
		result = Mathf.FloorToInt (xPosition - yPosition);
		if (result == 0) result = Mathf.FloorToInt (x.Hp-y.Hp);
		return result;
	}
}
