//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

//Archer->Rogue->Tank->Mage->Shaman->Archer
public class UnitBase:MonoBehaviour
{
	public int unitType;
	public int elementType;
	public int cost;
	protected float maxHP;
	protected float HP;
	protected float attackPower;
	protected float defensePower;
	protected int range;
	protected float coolDown;
	protected float coolDownFactor;
	protected int criticalRate;
	protected float criticalFactor;
	protected const float MIN_COOLDOWN = 0.5f;
	protected float movingSpeed = 0f;
	public UnitBase ()
	{
	}
	virtual public float getAttackPower(UnitBase targetUnit)
	{
		return attackPower;
	}
	virtual public float getDefensePower(UnitBase AttackerUnit)
	{
		return defensePower;
	}
	public int getRange()
	{
		return range;
	}
	public float getMaxHP()
	{
		return maxHP;
	}
	public float getHP()
	{
		return HP;
	}
	public void setHP(float newHP)
	{
		HP = newHP;
		Unit unit = gameObject.GetComponent<Unit> ();
		unit.updateHP();
	}
	public int getCriticalRate()
	{
		return criticalRate;
	}
	public float getCriticalFactor()
	{
		return criticalFactor;
	}
	public float getCoolDown()
	{
		return coolDown-coolDownFactor>MIN_COOLDOWN?coolDown-coolDownFactor:MIN_COOLDOWN;
	}
	public float getCoolDownFactor()
	{
		return coolDownFactor;
	}
	public void setCoolDownFactor(float factor)
	{
		coolDownFactor = factor;
	}
	public float getMovingSpeed()
	{
		return movingSpeed;
	}
}

