//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class UnitTypes
{
	public const int TANK = 1;
	public const int ROGUE = 2;
	public const int MAGE = 3;
	public const int ARCHER = 4;
	public const int SHAMAN = 5;
	public const int WATERELEMENT = 1;
	public const int FIREELEMENT = 2;
	public const int WOODELEMENT = 3;
	public UnitTypes ()
	{
	}
}
