//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class Warlord:UnitBase
{
	public Warlord ()
	{
		unitType = UnitTypes.WARLORD;
		this.attackPower = 100;
		this.defensePower = 50;
		this.range = 0;
		this.maxHP = 2500;
		this.HP = maxHP;
		criticalRate = 0;
		criticalFactor = 1f;
		coolDown =0f;
		coolDownFactor = 0f;
	}
}
